name: Trigger auto deployment for smartpark-frontend

on:
  push:
    branches:
      [ main ]
    paths:
    - 'frontend/**'
    - 'Dockerfile.frontend'
    - '.github/workflows/smartpark-frontend-AutoDeployTrigger-636293e1-ec3b-4455-96f1-6067c5d415b1.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.SMARTPARKFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SMARTPARKFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SMARTPARKFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: ./Dockerfile.frontend
          registryUrl: smartparkacr2025.azurecr.io
          registryUsername: ${{ secrets.SMARTPARKFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SMARTPARKFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: smartpark-frontend
          resourceGroup: smartpark-rg
          imageToBuild: smartparkacr2025.azurecr.io/smartpark-frontend:${{ github.sha }}
          buildArguments: |
            REACT_APP_API_URL=https://smartpark-backend.jollydune-54002bd0.eastasia.azurecontainerapps.io/api/v1
            REACT_APP_SOCKET_URL=https://smartpark-backend.jollydune-54002bd0.eastasia.azurecontainerapps.io
            REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
